servo_offsets:
  leg1_coxa: 0.0
  leg1_femur: 0.0
  leg1_tibia: 0.0
  leg2_coxa: 0.0
  leg2_femur: 0.0
  leg2_tibia: 0.0
  leg3_coxa: 0.0
  leg3_femur: 0.0
  leg3_tibia: 0.0
  leg4_coxa: 0.0
  leg4_femur: 0.0
  leg4_tibia: 0.0
  leg5_coxa: 0.0
  leg5_femur: 0.0
  leg5_tibia: 0.0
  leg6_coxa: 0.0
  leg6_femur: 0.0
  leg6_tibia: 0.0
