servo_offsets:
  leg1_coxa: -11.0, 
  leg1_femur: 25.0, 
  leg1_tibia: 120.0, 
  leg2_coxa: 10.0, 
  leg2_femur: 42.0, 
  leg2_tibia: 121.0, 
  leg3_coxa: 0.0, 
  leg3_femur: 53.0, 
  leg3_tibia: 114.0, 
  leg4_coxa: 7.0, 
  leg4_femur: -45.0, 
  leg4_tibia: -113.0, 
  leg5_coxa: -3.0, 
  leg5_femur: -50.0, 
  leg5_tibia: -116.0, 
  leg6_coxa: 9.0, 
  leg6_femur: -46.0, 
  leg6_tibia: -106.0,
